import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { DemoComponent } from './demo.component';
import { MainComponent } from './components';

import { SubModule } from '../demo/sub';
import { SpeechRecognitionModule } from '../../projects/ngx-speech-recognition/src/public_api';

@NgModule({
  declarations: [
    // app container.
    DemoComponent,

    // In MainComponent, we demonstrate using SpeechRecognitionService
    // generated by using SpeechRecognitionModule::withConfig in DemoModule.
    //
    // MainComponentでは、DemoModuleで
    // SpeechRecognitionModule::withConfigを使用して生成された
    // SpeechRecognitionServiceの使用方法を使用します。
    MainComponent,
  ],
  imports: [
    BrowserModule,
    CommonModule,
    RouterModule,
    SpeechRecognitionModule.withConfig({
      lang: 'en-US',

      interimResults: true,
      maxAlternatives: 10,
    }),
    SubModule,
  ],
  providers: [],
  bootstrap: [DemoComponent]
})
export class DemoModule { }
